name: Terraform Deployment

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "main"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using Managed Identity
        uses: azure/login@v1
        with:
          client-id: ${{ vars.UAMI_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUB_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./fabric_infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./fabric_infra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./fabric_infra
